export const LOADING = 'LOADING';
export const SUCCESS = 'SUCCESS';
export const ERROR = 'ERROR';
export const RESET = 'RESET';

export const GET_ORDERS = "GET_ORDERS";
export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const GET_ORDERS_ERROR = "GET_ORDERS_ERROR";

export const GET_COMPLETED_ORDERS = "GET_COMPLETED_ORDERS";
export const GET_COMPLETED_ORDERS_SUCCESS = "GET_COMPLETED_ORDERS_SUCCESS";
export const GET_COMPLETED_ORDERS_ERROR = "GET_COMPLETED_ORDERS_ERROR";

export const GET_APPROVED_ORDERS = "GET_APPROVED_ORDERS";
export const GET_APPROVED_ORDERS_SUCCESS = "GET_APPROVED_ORDERS_SUCCESS";
export const GET_APPROVED_ORDERS_ERROR = "GET_APPROVED_ORDERS_ERROR";

export const GET_ACTIVE_ORDERS = "GET_ACTIVE_ORDERS";
export const GET_ACTIVE_ORDERS_SUCCESS = "GET_ACTIVE_ORDERS_SUCCESS";
export const GET_ACTIVE_ORDERS_ERROR = "GET_ACTIVE_ORDERS_ERROR";

export const GET_REJECTED_ORDERS = "GET_REJECTED_ORDERS";
export const GET_REJECTED_ORDERS_SUCCESS = "GET_REJECTED_ORDERS_SUCCESS";
export const GET_REJECTED_ORDERS_ERROR = "GET_REJECTED_ORDERS_ERROR";

export const GET_CANCELLED_ORDERS = "GET_CANCELLED_ORDERS";
export const GET_CANCELLED_ORDERS_SUCCESS = "GET_CANCELLED_ORDERS_SUCCESS";
export const GET_CANCELLED_ORDERS_ERROR = "GET_CANCELLED_ORDERS_ERROR";

export const GET_PENDING_ORDERS = "GET_PENDING_ORDERS";
export const GET_PENDING_ORDERS_SUCCESS = "GET_PENDING_ORDERS_SUCCESS";
export const GET_PENDING_ORDERS_ERROR = "GET_PENDING_ORDERS_ERROR";

export const GET_WAITING_ASSIGN_ORDERS = "GET_WAITING_ASSIGN_ORDERS";
export const GET_WAITING_ASSIGN_ORDERS_SUCCESS = "GET_WAITING_ASSIGN_ORDERS_SUCCESS";
export const GET_WAITING_ASSIGN_ORDERS_ERROR = "GET_WAITING_ASSIGN_ORDERS_ERROR";

export const GET_ORDER = "GET_ORDER";
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS";
export const GET_ORDER_ERROR = "GET_ORDER_ERROR";

export const CREATE_ORDER = "CREATE_ORDER";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const CREATE_ORDER_ERROR = "CREATE_ORDER_ERROR";

export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const UPDATE_ORDER_ERROR = "UPDATE_ORDER_ERROR";

export const DELETE_ORDER= "DELETE_ORDER";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";
export const DELETE_ORDER_ERROR = "DELETE_ORDER_ERROR";
